const KEYWORDS = {
    if: "IF",
    whether: "IF",
    else: "ELSE",
    while: "WHILE",
    for: "FOR",
    function: "FUNCTION",
    switch: "SWITCH",
    case: "CASE",
    whido: "WHIDO",
    new: "NEW",
    def: "DEF",
    to: "ASSIGN",
    as: "AS",
    equals: "EQUALS",
    reallyequals: "REALLY_EQUALS",
    notequals: "NOT_EQUALS",
    reallynotequals: "REALLY_NOT_EQUALS",
    less: "LESS_THAN",
    greater: "GREATER_THAN",
    lessequals: "LESS_THAN_EQUALS",
    greaterequals: "GREATER_THAN_EQUALS",
    document: "DOCUMENT",
};
module.exports = KEYWORDS;